add product on the fly.
open-dex/conflux-dex pull request #12
Opened 2023-10-26 10:25 UTC by Tigo9527

2023-10-26 10:59 UTC, boqiu requested changes

2023-10-26 10:59 UTC, boqiu commented on src/main/java/conflux/dex/blockchain/EventBlockchain.java
> -		Validators.validateAddress(address, AddressType.Contract, "contract address");
Why removed?

2023-10-27 02:11 UTC, Tigo9527 commented on src/main/java/conflux/dex/blockchain/EventBlockchain.java
> -		Validators.validateAddress(address, AddressType.Contract, "contract address");
Legacy validation (checking address prefix 0x1 or 0x8) does not work in evm space.

2023-10-27 02:11 UTC, boqiu approved these changes

2023-10-27 02:13 UTC, merged